[versions]
coilVersion = "3.0.4"
composeShimmer = "1.0.5"
espressoCore = "3.7.0"
firebaseAdmin = "9.2.0"
firebaseAuthProvider = "1.5.0"
googleCloudStorage = "2.61.0"
junit = "1.3.0"
kotlinxCoroutines = "1.10.2"
kotlinxCoroutinesSwing = "1.10.2"
kotlinxSerializationJson = "1.9.0"
ktor = "3.3.3"
ktlint = "13.1.0"
ktx = "1.17.0"
material = "1.12.0"
materialIconsCore = "1.7.3"
platformtools = "0.7.4"
room = "2.8.4"
agp = "8.13.2"
kotlin = "2.2.21"
composeTest = "1.10.0"
webWorkerDriver = "2.2.1"
mockk = "1.14.7"
sqldelight = "2.2.1"
ksp = "2.2.21-2.0.4"
compose-multiplatform = "1.9.3"
dag-command = "1.14.0"
dokka = "2.1.0"
google-services = "4.4.2"
logback-classic = "1.5.18"
hikaricp = "7.0.2"
postgresql = "42.7.8"
compose-navigation = "2.9.1"
publish = "0.33.0"
lifecycleViewmodelCompose = "2.9.6"
compileSdk = "36"
targetSdk = "36"
minSdk = "26"
mixpanel = "8.0.3"

[libraries]
activity-compose = { module = "androidx.activity:activity-compose" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
androidx-compose-test = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "composeTest" }
androidx-compose-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "composeTest" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "junit" }
androidx-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "ktx" }
androidx-material3 = { module = "androidx.compose.material3:material3" }
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coilVersion" }
coil-ktor3 = { module = "io.coil-kt.coil3:coil-network-ktor3", version.ref = "coilVersion" }
coil-video = { module = "io.coil-kt.coil3:coil-video", version.ref = "coilVersion" }
compose-shimmer = { module = "com.valentinilk.shimmer:compose-shimmer", version.ref = "composeShimmer" }
firebase-admin = { module = "com.google.firebase:firebase-admin", version.ref = "firebaseAdmin" }
firebase-auth-provider = { module = "com.kborowy:firebase-auth-provider", version.ref = "firebaseAuthProvider" }
google-cloud-storage = { module = "com.google.cloud:google-cloud-storage", version.ref = "googleCloudStorage" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
kotlin-coroutines-reactor = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-reactor", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutines" }
ktor-server-auth = { module = "io.ktor:ktor-server-auth" }
ktor-server-auth-jwt = { module = "io.ktor:ktor-server-auth-jwt" }
ktor-server-cors = { module = "io.ktor:ktor-server-cors", version.ref = "ktor" }
ktor-server-swagger = { module = "io.ktor:ktor-server-swagger" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
kotlinx-coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinxCoroutinesSwing" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutines" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
ktor-client-auth = { module = "io.ktor:ktor-client-auth", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-client-websockets = { module = "io.ktor:ktor-client-websockets", version.ref = "ktor" }
ktor-serialization-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-server-content-negotiation = { module = "io.ktor:ktor-server-content-negotiation", version.ref = "ktor" }
ktor-server-websocket = { module = "io.ktor:ktor-server-websockets-jvm" }
ktor-server-cio = { module = "io.ktor:ktor-server-cio" }
ktor-server-tests = { module = "io.ktor:ktor-server-test-host", version.ref = "ktor" }
material-icons-core = { module = "org.jetbrains.compose.material:material-icons-core", version.ref = "materialIconsCore" }
platformtools-darkmodedetector = { module = "io.github.kdroidfilter:platformtools.darkmodedetector", version.ref = "platformtools" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-paging = { group = "androidx.room", name = "room-paging", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
sqldelight-jvm = { group = "app.cash.sqldelight", name = "sqlite-driver", version.ref = "sqldelight" }
sqldelight-dialect-postgres = { group = "app.cash.sqldelight", name = "postgresql-dialect", version.ref = "sqldelight" }
sqldelight-dialect-sqlite = { group = "app.cash.sqldelight", name = "sqlite-3-30-dialect", version.ref = "sqldelight" }
sqldelight-native = { module = "app.cash.sqldelight:native-driver", version.ref = "sqldelight" }
sqldelight-jdbc-driver = { group = "app.cash.sqldelight", name = "jdbc-driver", version.ref = "sqldelight" }
kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlin" }
logback-classic = { group = "ch.qos.logback", name = "logback-classic", version.ref = "logback-classic" }
database-hikaricp = { group = "com.zaxxer", name = "HikariCP", version.ref = "hikaricp" }
database-postgresql = { group = "org.postgresql", name = "postgresql", version.ref = "postgresql" }
compose-navigation = { group = "org.jetbrains.androidx.navigation", name = "navigation-compose", version.ref = "compose-navigation" }
sqldelight-web-driver = { module = "app.cash.sqldelight:web-worker-driver", version.ref = "webWorkerDriver" }
lifecycle-viewmodel-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleViewmodelCompose" }
mixpanel-android = { module = "com.mixpanel.android:mixpanel-android", version.ref = "mixpanel" }
ktor-client-js = { module = "io.ktor:ktor-client-js", version.ref = "ktor" }

[plugins]
application = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
nativeCocoapods = { id = "org.jetbrains.kotlin.native.cocoapods", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
org-jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
sqldelight = { id = "app.cash.sqldelight", version.ref = "sqldelight" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
dag-command = { id = "io.github.leandroborgesferreira.dag-command", version.ref = "dag-command" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
google-services = { id = "com.google.gms.google-services", version.ref = "google-services" }
ktor-framework = { id = "io.ktor.plugin", version.ref = "ktor" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
compose-multiplatform-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
sonatype-publish = { id = "com.vanniktech.maven.publish", version.ref = "publish" }
